### PR TITLE
fix: Hover links on dark mode

### PR DESCRIPTION
**Pull request by Itezaz-ul-Hassan**
This PR fixes the hover link issues while in dark mode

### CODE REVIEW

**Comment by Itezaz-ul-Hassan** [comment]
@JuanPabloDiaz This PR fixes the issue specified in this [issue](https://github.com/JuanPabloDiaz/youtube/issues/6)

**Comment by Itezaz-ul-Hassan** [comment]
@JuanPabloDiaz Please Review it and merge it.

**Comment by Itezaz-ul-Hassan** [comment]
@JuanPabloDiaz Can you add `hacktoberfest` and `hacktoberfest-accepted` labels on this PR. Thanks

**Comment by JuanPabloDiaz** [comment]
I don't approve the change.

**Pull request closed without merging**
